package mailfmt

import (
	"bytes"
	"strings"
	"testing"
)

// A simple multipart message: text/plain + text/html + attachment.
const sampleMultipart = `From: =?UTF-8?B?QWxpY2UgQW5kcsOpc2Vu?= <alice@example.org>
To: bridge@example.com, bob@example.com
Cc: carol@example.com
Subject: =?utf-8?q?Ol=C3=A1_=E2=82=AC_world?=
Message-ID: <abc123@example.org>
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="BOUND"

--BOUND
Content-Type: multipart/alternative; boundary="INNER"

--INNER
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

Hello=20plain=20world!
--INNER
Content-Type: text/html; charset=utf-8

<html><body><p>Hello html world!</p></body></html>
--INNER--
--BOUND
Content-Type: text/plain; name=notes.txt
Content-Disposition: attachment; filename="notes.txt"

attached content
--BOUND--
`

func TestParseMail(t *testing.T) {
	in, err := ParseMail([]byte(sampleMultipart), 1<<20)
	if err != nil {
		t.Fatal(err)
	}
	if in.FromName != "Alice Andrésen" {
		t.Errorf("FromName = %q", in.FromName)
	}
	if in.FromAddr != "alice@example.org" {
		t.Errorf("FromAddr = %q", in.FromAddr)
	}
	if in.Subject != "Olá € world" {
		t.Errorf("Subject = %q", in.Subject)
	}
	if in.Text != "Hello plain world!" {
		t.Errorf("Text = %q", in.Text)
	}
	if len(in.ToAddrs) != 3 {
		t.Errorf("ToAddrs = %v", in.ToAddrs)
	}
	if len(in.Attachments) != 1 {
		t.Fatalf("attachments = %d", len(in.Attachments))
	}
	att := in.Attachments[0]
	if att.Name != "notes.txt" || string(att.Data) != "attached content" {
		t.Errorf("attachment = %+v", att)
	}
	if in.LoopMarker {
		t.Error("LoopMarker should be false")
	}
}

const sampleHTMLOnly = `From: html@example.org
Subject: HTML only
MIME-Version: 1.0
Content-Type: text/html; charset=utf-8

<html><body><p>This is <b>bold</b> text</p></body></html>
`

func TestParseMailHTMLFallback(t *testing.T) {
	in, err := ParseMail([]byte(sampleHTMLOnly), 0)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(in.Text, "bold") || strings.Contains(in.Text, "<") {
		t.Errorf("Text = %q, want plain text containing 'bold'", in.Text)
	}
}

const sampleLoop = `From: bridge@example.com
Subject: generated by us
X-Mattermail-Sent: 1

body
`

func TestParseMailLoopMarker(t *testing.T) {
	in, err := ParseMail([]byte(sampleLoop), 0)
	if err != nil {
		t.Fatal(err)
	}
	if !in.LoopMarker {
		t.Error("LoopMarker should be true")
	}
}

func TestParseMailAttachmentCap(t *testing.T) {
	in, err := ParseMail([]byte(sampleMultipart), 5) // 5 bytes cap
	if err != nil {
		t.Fatal(err)
	}
	if len(in.Attachments) != 0 {
		t.Errorf("attachments = %d, want 0", len(in.Attachments))
	}
	if len(in.SkippedFiles) != 1 || in.SkippedFiles[0] != "notes.txt" {
		t.Errorf("SkippedFiles = %v", in.SkippedFiles)
	}
}

func TestComposeMailRoundTrip(t *testing.T) {
	raw, err := ComposeMail(OutgoingMail{
		FromName: "MatterMail",
		FromAddr: "bridge@example.com",
		To:       []string{"alice@example.org"},
		Subject:  "Olá mundo €",
		Body:     "first line\nsecond line",
		Attachments: []Attachment{
			{Name: "data.bin", ContentType: "application/octet-stream", Data: []byte{0, 1, 2, 255}},
		},
	})
	if err != nil {
		t.Fatal(err)
	}

	in, err := ParseMail(raw, 1<<20)
	if err != nil {
		t.Fatal(err)
	}
	if in.Subject != "Olá mundo €" {
		t.Errorf("Subject = %q", in.Subject)
	}
	if in.Text != "first line\nsecond line" {
		t.Errorf("Text = %q", in.Text)
	}
	if !in.LoopMarker {
		t.Error("outgoing mail must carry the loop marker")
	}
	if len(in.Attachments) != 1 || in.Attachments[0].Name != "data.bin" {
		t.Fatalf("attachments = %+v", in.Attachments)
	}
	if !bytes.Equal(in.Attachments[0].Data, []byte{0, 1, 2, 255}) {
		t.Errorf("attachment data = %v", in.Attachments[0].Data)
	}
	if in.FromAddr != "bridge@example.com" {
		t.Errorf("FromAddr = %q", in.FromAddr)
	}
}

func TestComposeMailNoAttachment(t *testing.T) {
	raw, err := ComposeMail(OutgoingMail{
		FromAddr: "bridge@example.com",
		To:       []string{"a@example.org"},
		Subject:  "s",
		Body:     "b",
	})
	if err != nil {
		t.Fatal(err)
	}
	in, err := ParseMail(raw, 1<<20)
	if err != nil {
		t.Fatal(err)
	}
	if in.Text != "b" || len(in.Attachments) != 0 {
		t.Errorf("parsed = %+v", in)
	}
}
